apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-app
  labels:
    app: qr-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qr-app
    spec:
      # nodeSelector:
      #   node: node-1
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "value"
        effect: "NoSchedule"
      containers:
      - image: ${FRONTEND_IMAGE}
        name: devops-qr-front-end
        ports:
        - containerPort: 3000 # container port 
        # env:
        #   - name: REACT_APP_BACKEND_URL 
        #     valueFrom:
        #       configMapKeyRef:
        #         name: front-end-service
        #         key: REACT_APP_BACKEND_URL
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: qr-app-service
spec:
  selector:
    app: qr-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80 # 80 on which port you want to run the service 
    targetPort: 3000 # where the nextjs pod is running 