apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-app
  labels:
    app: qr-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr-app
  template:
    metadata:
      labels:
        app: qr-app
    spec:
      containers:
      - image: ${FRONTEND_IMAGE}
        name: devops-qr-front-end
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: qr-app-service
spec:
  selector:
    app: qr-app
  # type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000